const studentsData = [
	{
		id: 0,
		fname: "Richard",
		lname: "Betalmos",
		username: "IchadB",
		email: "ichad@gmail.com",
		contact: 09925235991,
		gender: "Male",
		age: 30,
		password: "1234ichad",
		type: "student",
	},
	{
		id: 1,
		fname: "Ferdie",
		lname: "Nodalo",
		username: "NodaloF",
		email: "nodalof@gmail.com",
		contact: 09951234567,
		gender: "Male",
		age: 21,
		password: "1234ferdie",
		type: "student",
	},
	{
		id: 2,
		fname: "Jacob",
		lname: "Eugenio",
		username: "EugenioJ",
		email: "jacob@gmail.com",
		contact: 09123456786,
		gender: "Male",
		age: 32,
		password: "1234jacob",
		type: "student",
	},
];

module.exports = studentsData;
